### model
model_name_or_path: /home/pingbowen/models/Llama3.1-8b-instruct

### method
stage: rm
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: ultrafeedback
template: llama3
cutoff_len: 1024
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/reward
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
